# Introduction To Programming - More Stuff
# Launch School
# Kenny Chong
# 4/18/2016

1. Write a program that checks if sequence of characters "lab" exists in following string. If it does exist, print out the word.
Strings = ["laboratory". "experiment", "Pans Labyrinth", "elaborate", "polar bear"]
Solution: Strings.each do |s|
            if /labl/i.match(s) # /lab/ =~ word
              puts s
            end
          end

2. What will following program print to screen?
def execute(&block)
  block
end
execute { puts "Hello from inside the execute method!"}
Solution: Nothing is printed because block.call was not called inside the execute method.

3. What is exception handling and what problem does it solve?
Exception handling is mechanism that handles bad inputs and errors in a graceful manner. It prevents
errors from halting the execution of our code. (A way of handling errors by changing the flow of control
without exiting the program entirely).

4. Modify execerise 2 to make block execute properly.
Solution: def execute(&block)
            block.call
          end

5. What does the following code...
def execute(block)
  block.call
end

execute {puts "Hello from inside the execute method!"}

Give us the following error when we run it?

block.rb1:in `execute': wrong number of arguments (0 for 1) (ArgumentError)
from test.rb:5:in `<main>'

Solution: Need &block instead of block as argument.